# Generated by Django 2.2.24 on 2021-11-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=5)),
                ('weight', models.IntegerField()),
                ('repetitions', models.IntegerField()),
            ],
        ),
    ]
